## Developer information
## Name: Md Siamul Islam Soaib
## Email: soaib.softdev@gmail.com

## === Project Info === ##
name: ilm
description: "A new Flutter project."
publish_to: 'none'

## === Version === ##
version: 1.0.0+1
environment:
  sdk: ^3.8.1

## === Dependencies === ##
dependencies:
  flutter:
    sdk: flutter

  ## === Icons and Fonts === ##
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.12.0

  ## === State Management === ##
  get: ^4.7.2

  ## === HTTP and API === ##
  http: ^1.5.0

  ## === Local Storage === ##
  shared_preferences: ^2.5.3

  ## === Loading and Progress Indicators === ##
  flutter_spinkit: ^5.2.2
  shimmer: ^3.0.0

  ## === Image Handling === ##
  cached_network_image: ^3.2.3

  ## === Date and Time === ##
  intl: ^0.20.2
  timeago: ^3.7.1

  ## === Pull to Refresh === ##
  pull_to_refresh: ^2.0.0

  ## === Connectivity === ##
  connectivity_plus: ^7.0.0

  ## === URL Launcher === ##
  url_launcher: ^6.3.2

  ## === In-App Review === ##
  in_app_review: ^2.0.11

  ## === App Version Info === ##
  package_info_plus: ^9.0.0

  ## === Device Info === ##
  device_info_plus: ^12.1.0

  ## === Image Picker === ##
  image_picker: ^1.2.0

  ## === File Picker === ##
  file_picker: ^10.3.3

  ## === Quran === ##
  quran: ^1.4.1

#  ## === Video Player === ##
#  video_player: ^2.6.1
#  ## === Audio Player === ##
#  just_audio: ^0.9.37
#  audio_session: ^0.1.6

## === Dev Dependencies === ##
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


## === Assets === ##
flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/bg/